# Generated by Django 5.2.4 on 2025-09-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_phone"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
